apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        rewrite name gitpod.szab100.com internal-gitpod-int-us-west-2-1554481249.us-west-2.elb.amazonaws.com
        rewrite name regex (.*)\.gitpod.szab100.com internal-gitpod-int-us-west-2-1554481249.us-west-2.elb.amazonaws.com answer auto
        rewrite name regex (.*)\.ws\.gitpod.szab100.com internal-gitpod-int-us-west-2-1554481249.us-west-2.elb.amazonaws.com answer auto
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    health\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n      pods insecure\n      fallthrough in-addr.arpa ip6.arpa\n    }\n    prometheus :9153\n    forward . /etc/resolv.conf\n    cache 30\n    loop\n    reload\n    loadbalance\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"eks.amazonaws.com/component":"coredns","k8s-app":"kube-dns"},"name":"coredns","namespace":"kube-system"}}
  creationTimestamp: "2021-09-30T22:04:34Z"
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system
  resourceVersion: "46431"
  uid: 944e31b3-60f0-449b-9fb1-f20f871cdf5b
