apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: |-
      {
        "Type": "redirect",
        "RedirectConfig": {
          "Protocol": "HTTPS",
          "Port": "443",
          "StatusCode": "HTTP_301"
        }
      }
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:045575647522:certificate/ee010d2f-3b7c-4b71-ba79-078adf59e721
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/listen-ports: |-
      [{
        "HTTP": 80
      }, {
        "HTTPS": 443
      }]
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=3600
    alb.ingress.kubernetes.io/load-balancer-name: gitpod-int-us-west-2
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
    alb.ingress.kubernetes.io/tags: Purpose=Gitpod,Service=proxy
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30
    alb.ingress.kubernetes.io/target-node-labels: gitpod.io/workload_workspaces=true
    kubernetes.io/ingress.class: alb
  name: gitpod-int
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: proxy
            port:
              number: 443
        path: /
        pathType: Prefix
